/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 pokemon.glb --transform --types -k
Author: Wesai (https://sketchfab.com/Wesai)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-firered-players-room-b23b6b253207463c97db2a7092adff74
Title: Pokemon FireRed - Player's Room
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import type { Mesh } from "three/src/objects/Mesh";
import type { MeshBasicMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    base_fireRed_material_0: Mesh;
    tiles_fireRed_material_0: Mesh;
    chair_fireRed_material_0: Mesh;
    table_fireRed_material_0: Mesh;
    Computer_fireRed_material_0: Mesh;
    TV_stand_fireRed_material_0: Mesh;
    TV_fireRed_material_0: Mesh;
    carpet_A_fireRed_material_0: Mesh;
    carpet_B_fireRed_material_0: Mesh;
    bed_fireRed_material_0: Mesh;
    dresser_fireRed_material_0: Mesh;
    bookShelf_fireRed_material_0: Mesh;
    NES_fireRed_material_0: Mesh;
    railing_fireRed_material_0: Mesh;
    stairs_fireRed_material_0: Mesh;
    wall_picture_fireRed_material_0: Mesh;
    ambient_occlusion_fireRed_material_0: Mesh;
    title_fireRed_material_0: Mesh;
  };
  materials: {
    fireRed_material: MeshBasicMaterial;
  };
};

export function Pokemon(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/pokemon-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} receiveShadow>
      <mesh
        name="base_fireRed_material_0"
        geometry={nodes.base_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="tiles_fireRed_material_0"
        geometry={nodes.tiles_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="chair_fireRed_material_0"
        geometry={nodes.chair_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="table_fireRed_material_0"
        geometry={nodes.table_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="Computer_fireRed_material_0"
        geometry={nodes.Computer_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="TV_stand_fireRed_material_0"
        geometry={nodes.TV_stand_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="TV_fireRed_material_0"
        geometry={nodes.TV_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="carpet_A_fireRed_material_0"
        geometry={nodes.carpet_A_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="carpet_B_fireRed_material_0"
        geometry={nodes.carpet_B_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="bed_fireRed_material_0"
        geometry={nodes.bed_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="dresser_fireRed_material_0"
        geometry={nodes.dresser_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="bookShelf_fireRed_material_0"
        geometry={nodes.bookShelf_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="NES_fireRed_material_0"
        geometry={nodes.NES_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="railing_fireRed_material_0"
        geometry={nodes.railing_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="stairs_fireRed_material_0"
        geometry={nodes.stairs_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="wall_picture_fireRed_material_0"
        geometry={nodes.wall_picture_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="ambient_occlusion_fireRed_material_0"
        geometry={nodes.ambient_occlusion_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        name="title_fireRed_material_0"
        geometry={nodes.title_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
    </group>
  );
}

useGLTF.preload("/pokemon-transformed.glb");
